class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'dl'
        self.UnzipMirrorCommand = 'extract'
        self.TarMirrorCommand = 'tardl'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'stop'
        self.ListCommand = 'search'
        self.SpeedCommand = 'speedtest'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.CloneCommand = "clone"
        self.WatchCommand = 'ytdl'
        self.TarWatchCommand = 'tarytdl'
        self.DeleteCommand = 'del'
        self.clnCommand = 'cln'
        self.UsageCommand = 'usage'
        self.SystemstatsCommand= 'system'
        self.WikiCommand= 'wiki'
        self.TotranslateCommand = 'tr'
        self.PasteCommand = 'paste'
        self.systemkutestCommand = 'neofetch'
        self.AuthorizedUsersCommand = 'users'
        
BotCommands = _BotCommands()
