class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'dl2'
        self.UnzipMirrorCommand = 'extract2'
        self.TarMirrorCommand = 'tardl2'
        self.CancelMirror = 'cancel2'
        self.CancelAllCommand = 'stop2'
        self.ListCommand = 'search'
        self.SpeedCommand = 'speedtest'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'auth2'
        self.UnAuthorizeCommand = 'unauthorize2'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.CloneCommand = "clone2"
        self.WatchCommand = 'ytdl'
        self.TarWatchCommand = 'tarytdl2'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.AuthorizedUsersCommand = 'users'
	self.SystemstatsCommand= 'system'
        self.WikiCommand= 'wiki'
        self.TotranslateCommand = 'tr'
        self.PasteCommand = 'paste'
        self.systemkutestCommand = 'neofetch'
        
BotCommands = _BotCommands()
